name: New Item
description: Submit a new item to be rated.
title: "[Item] <Short title here>"
labels: ["type:item"]
body:
  - type: input
    id: url
    attributes:
      label: Source URL
      description: Paste the original link for this item.
      placeholder: https://example.com/article
    validations:
      required: true
  - type: input
    id: thumbnail
    attributes:
      label: Thumbnail URL
      description: Paste an image URL (OG image, screenshot, or hosted image).
      placeholder: https://...
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short summary. Keep it concise.
      placeholder: A few sentences that capture the essence.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Optional Notes
      description: Any extra details.
      placeholder: (optional)
    validations:
      required: false
