name: New Item
description: Submit a new item to be rated.
title: "[Item] <Short title here>"
labels: ["type:item"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a new item! Fill out the fields below. The site reads the YAML block at the top, so keep the headings as-is.
  - type: input
    id: url
    attributes:
      label: Source URL
      description: Paste the original link for this item.
      placeholder: https://example.com/article
    validations:
      required: true
  - type: input
    id: thumbnail
    attributes:
      label: Thumbnail URL
      description: Paste an image URL (OG image, screenshot, or hosted image).
      placeholder: https://...
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short summary. Keep it concise.
      placeholder: A few sentences that capture the essence.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Optional Notes
      description: Any extra details.
      placeholder: (optional)
    validations:
      required: false
  - type: textarea
    id: body
    attributes:
      label: Issue body
      description: Leave the YAML block intact; add extra notes below it.
      render: markdown
      placeholder: |
        ---
        schema: v1
        url: <Paste the source URL here>
        thumbnail: <Optional image URL>
        summary: >
          Concise human-written summary.
        ---

        Additional notes (optional)
    validations:
      required: true
